export const MobileProjects = [
  {
    num: "01",
    title: "Ringfill",
    img: "/images/Project/rfApp.png",
    skills: "React Native, TypeScript, Figma",
    description: `Recharging mobile app that allows the user to recharge anywhere & anytime using various payment methods. I have designed and developed the mobile app UI.`,
    github: "https://github.com/aheart500/Ringfill",
    playstore:
      "https://play.google.com/store/apps/details?id=com.yusawireless.ringfill",
    figma:
      "https://www.figma.com/design/SMEFZsuyDzD7ao7rYcsoxI/Untitled?m=auto&t=cqv5s988Lkrtp8Ix-6",
  },
  {
    num: "02",
    title: "MedC",
    img: "/images/Project/medcPhone.png",
    skills: "React Native, TypeScript",
    description: `Educational app for medical students with a vast collection of questions and answer explanations. I developed the mobile app UI for a user-friendly experience.`,
    github: "https://github.com/aheart500/MedC",
  },
  {
    num: "03",
    title: "Delivery App",
    img: "/images/Project/delivery.png",
    skills: "React Native",
    description: `A user-friendly mobile delivery app focused on providing an intuitive experience for tracking orders and browsing delivery options.`,
    github: "https://github.com/Karim248119/K-Dlivery",
  },
  {
    num: "05",
    title: "Babel Library",
    img: "/images/Project/babelApp.png",
    skills: "React Native, TypeScript",
    description: `Library app offering a comprehensive book collection with a search bar, reading progress tracker, and a feature for adding favorite quotes.`,
    github: "https://github.com/Karim248119/Babel-Library",
  },
  {
    num: "04",
    title: "Heavenly Restriction",
    img: "/images/Project/HR.png",
    skills: "React Native, MongoDB, Express.JS, TypeScript, Figma",
    description: `Inspired by Jujutsu Kaisen, this healthcare app includes fitness programs, diet plans, and a BMI calculator, with exercise demos to guide users.`,
    github: "https://github.com/Karim248119/Heavenly-Restriction",
  },
  {
    num: "05",
    title: "Night Activities",
    img: "/images/Project/na.png",
    skills: "React Native, TypeScript, Firebase, Figma, Canva",
    description: `A couples app for saving and sharing activities. Includes TODO management, a Shared Gallery, Saved Recipes, and a Watch List stack for IMDB movies.`,
    figma:
      "https://www.figma.com/design/evOWv5bNFT0ptlfrLXJ3kr/NA?m=auto&t=qYNbn13d2TdLqKBo-6",
  },
  {
    num: "06",
    title: "Lady Store",
    img: "/images/Project/lsApp.png",
    skills: "React Native, Figma, Canva",
    description: `Women's E-store app with CRUD functionality for managing products, ensuring an attractive and user-friendly interface.`,
    github: "https://github.com/Karim248119/Lady-Store",
  },
];

export const WebProjects = [
  {
    num: "01",
    title: "Ringfill",
    img: "/images/Project/RF.png",
    skills: "Next.JS, Tailwind, TypeScript",
    description: `Recharge website that allows users to recharge using various payment methods. I contributed by making edits on the website.`,
    github: "https://github.com/aheart500/Ringfill",
    web: "https://ringfill.com/",
  },
  {
    num: "02",
    title: "MedC",
    img: "/images/Project/medC.png",
    skills: "Next.JS, Tailwind, Shadcn/UI, TypeScript",
    description: `Educational website for medical students with a vast collection of questions and answer explanations. Applied Shadcn UI for enhanced usability.`,
    github: "https://github.com/aheart500/MedC",
  },
  {
    num: "03",
    title: "UnityCare",
    img: "/images/Project/ucWeb.png",
    skills: "Next.JS, Tailwind, TypeScript",
    description: `Healthcare platform offering online appointment booking, doctor and specialty information, and medical news for streamlined patient-administrator interactions.`,
    github: "https://github.com/Karim248119/hospital",
    web: "https://unitycare.vercel.app/",
  },
  {
    num: "04",
    title: "M-market",
    img: "/images/Project/M-market.png",
    skills: "React.JS, Tailwind",
    description: `E-marketplace with CRUD functionality, user authentication, payment stack, and search functionality for seamless online shopping.`,
    github: "https://github.com/Karim248119/Martian-Market",
    web: "https://karim248119.github.io/Martian-Market/",
  },
  {
    num: "05",
    title: "Babel Library",
    img: "/images/Project/blWeb.png",
    skills: "Next.JS, Tailwind, Shadcn/UI, Firebase, TypeScript",
    description: `Dashboard website for a library app that allows admin to performan all the CRUD operation on the books`,
    github: "https://github.com/Karim248119/Babel-Library",
  },
  {
    num: "06",
    title: "Petadopt",
    img: "/images/Project/pet.png",
    skills: "Next.JS, Tailwind",
    description: `Pet adoption site with a filtering feature and stories from previous adopters to enhance the user experience and encourage adoptions.`,
    github: "https://github.com/Karim248119/Petadopt",
    web: "https://k-petadopt.netlify.app/",
  },
  {
    num: "07",
    title: "COSMOS",
    img: "/images/Project/cosmos.png",
    skills: "Next.JS, Tailwind, TypeScript, Shadcn/ui, three.js, Framer motion",
    description: `COSMOS is a visually immersive tribute to the renowned science show, exploring the universe with stunning 3D visuals and animations. Built with Next.js, Tailwind CSS, and TypeScript, it features Three.js and Framer Motion for a captivating experience. Currently optimized for desktop, this project offers a unique, interactive journey through space.`,
    github: "https://github.com/Karim248119/COSMOS",
    web: "https://cosmos-red.vercel.app/",
  },
  {
    num: "08",
    title: "K-store",
    img: "/images/Project/kstore.png",
    skills: "React.JS, Tailwind",
    description: `E-commerce site featuring a wishlist, shopping cart, and multiple payment methods for a smooth shopping experience.`,
    github: "https://github.com/Karim248119/K-store",
    web: "https://k-commerce.netlify.app/",
  },

  {
    num: "09",
    title: "TOP-20",
    img: "/images/Project/top.png",
    skills: "React.JS, Tailwind",
    description: `A sleek, responsive webpage with dynamic content and smooth user experience.`,
    web: "https://top-20.netlify.app/",
  },
  {
    num: "10",
    title: "Movie List",
    img: "/images/Project/movies.png",
    skills: "React.JS, Tailwind",
    description: `A website where you can get a list of popular, upcoming, trending and top-rated movies with a full details about each movie. You can search movie my name also`,
    web: "https://karim248119.github.io/Movies/",
  },
  {
    num: "11",
    title: "Sherlock Holmes",
    img: "/images/Project/sherlock.png",
    skills: "HTML, Tailwind, JavaScript",
    description: `Landing page for Sherlock Holmes featuring responsive design and elegant styling that showcases his career and notable cases.`,
    web: "https://karim248119.github.io/Portfolio/",
    github: "https://github.com/Karim248119/Portfolio",
  },
  {
    num: "12",
    title: "ANGORA",
    img: "/images/Project/ANGORA.png",
    skills: "HTML, Tailwind, JavaScript",
    description: `A simple, clean landing page for a company, providing essential business information with elegant styling.`,
    web: "https://karim248119.github.io/ANGORA/",
    github: "https://github.com/Karim248119/ANGORA",
  },
  {
    num: "13",
    title: "Bakery",
    img: "/images/Project/bakery.png",
    skills: "HTML, CSS, JavaScript",
    description: `A landing page for a bakery, showcasing products and company information in a visually appealing manner.`,
    web: "https://karim248119.github.io/Bakery/",
    github: "https://github.com/Karim248119/Bakery",
  },
];
